config/routes.rb
SistemaDeQuejas::Application.routes.draw do
  root  :to=>"tickets#index"
  
  get "tickets/:status" => "tickets#index", 
    :constraints=>{:status=>/pending|active|finished/}, 
    :as=>'tickets_by_status'
    
  resources :tickets do    
    resources :changes
  end
  
  
  match "login"           =>  'access#new'
  match "logout"          =>  'access#destroy'
  match "authenticate"    =>  'access#create'
  match "users/:id"       =>  "users#show"
  
  get "tickets/report/:format"	=>	"tickets#index",
  	:as =>	"report_tickets"
  get "managers"  =>  "managers#index",
    :as =>  "managers"
  get "attachment/:id"  =>  "attachments#show",
    :as=>"show_attachment"
  get "ticket/info" =>  "tickets#info"
  post  "ticket_taker/:id"  =>  "managers#ticket_taker",
    :as => "ticket_taker"
  post  "/post/:post_id/comments" =>  "comments#create",
    :as => :post_comments
  post  "tickets/:id" =>  "tickets#close",
    :as   =>  :close_ticket
 
end

app/models/comment.rb
class Comment < Post
  belongs_to :responsible , :class_name =>  "User"
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :require_user
  
  def create
    @post     = Post.find(params[:post_id])
    @comment  = @post.comments.build(params[:comment])
    @comment.responsible  = @current_user
    if @comment.save
      respond_to  do |format|
        format.js{}
        format.html{redirect_to ticket_path(@comment.ticket), :notice =>  "Comentado" }
      end
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.haml
=div_for comment do
  %p
    %author=comment.responsible.name rescue nil
    el
    %date=comment.created_at.to_formatted_s(:short)
    dijo:
  %quote=comment.body

app/views/comments/_comment_form.html.haml
.comment
  = image_tag('icons/comment_add.png')
  =link_to_function "Comentar", :id=>"toggleComment"

  #new_comment{:style=>"display:none"}
    %i #{@current_user.name} dice:
    =form_for [post, post.comments.build], :url=>post_comments_path(post.id), :remote  =>  :true, :html=>{:id=>post.id}  do |t|
      =t.text_area :body
      .actions
        =t.submit "Comentar"