config/routes.rb
SistemaDeQuejas::Application.routes.draw do
  root  :to=>"tickets#index"
  
  get "tickets/:status" => "tickets#index", 
    :constraints=>{:status=>/pending|active|finished/}, 
    :as=>'tickets_by_status'
    
  resources :tickets do    
    resources :changes
  end
  
  
  match "login"           =>  'access#new'
  match "logout"          =>  'access#destroy'
  match "authenticate"    =>  'access#create'
  match "users/:id"       =>  "users#show"
  
  get "tickets/report/:format"	=>	"tickets#index",
  	:as =>	"report_tickets"
  get "managers"  =>  "managers#index",
    :as =>  "managers"
  get "attachment/:id"  =>  "attachments#show",
    :as=>"show_attachment"
  get "ticket/info" =>  "tickets#info"
  post  "ticket_taker/:id"  =>  "managers#ticket_taker",
    :as => "ticket_taker"
  post  "/post/:post_id/comments" =>  "comments#create",
    :as => :post_comments
  post  "tickets/:id" =>  "tickets#close",
    :as   =>  :close_ticket
 
end

app/models/ticket.rb
class Ticket < Post #ActiveRecord::Base
  # Arreglo de posibles estados de la queja 
  STATUS              =   [:pending,  :active,  :finished].map(&:to_s).freeze
  STATUS_MSGS         =   { :pending  =>  "Tu queja esta en espera de que un administrativo lea y se haga cargo de tu queja",
                            :active   =>  "La queja esta siendo procesada en espera de una respuesta.",
                            :finished =>  "Se ha cerrado el ciclo de tu queja."  }
  CORRESPONDING_MAP   =   {:curso           =>  [:profesor, :contenido, :calificacion],
                           :administrativo  =>  [:empleado, :general],
                           :plataforma      =>  [:cuenta, :portal],
                           :otro            =>  [:otro]}
                          .freeze
  CORRESPONDING_TO    =   CORRESPONDING_MAP.values.flatten.map(&:to_s).freeze
  
  ## Atributo para controlar el usuario actual.
  cattr_accessor  :current_user ## DO NOT REMOVE OR CHANGE. Used in :responsible_management
  
  default_scope order('created_at ASC')
  
  # Relaciones con otras clases
  #
  belongs_to  :student  ,     :class_name =>  'User', :foreign_key  =>  'student_id'
  validates_associated  :student
  #   belongs_to  :teacher
  #   belongs_to  :course
  belongs_to  :responsible  , :class_name =>  'User', :foreign_key  =>  'responsible_id'
  # 
  #   Se descomentara mas adelante cuando se tenga mas idea sobre la implementacion.
  with_options :dependent =>  :destroy  do |ticket|
    ticket.has_many  :changes, :inverse_of=>:ticket
    ticket.has_many  :comments
  end
  
  ## Validators
  #validates :student,           :presence   =>  true :: not longer needed because of sessions.
  validates :corresponding_to,  :inclusion  =>  {:in => CORRESPONDING_TO}
  validates :title,       :presence =>  true
  
  ## Scopes
  scope :pending, where(:status=>STATUS.first).includes(:student, :responsible)    ## Would be great to keep DRY here. how?
  scope :active,  where(:status=>STATUS[1])   .includes(:student, :responsible)
  scope :finished,where(:status=>STATUS.last) .includes(:student, :responsible)
  scope :complete,  includes(:responsible, 
                              :student, 
                              :attachments,
                              :comments,
                              {:changes=>[:responsible, 
                                          :attachments, :comments]})
#  This Scope is now deprecated. We better use the method old? to know if its an old ticket
#  scope	:urgent , where(:updated_at => (Date.today-5.months..Date.today))

  ## Callbacks before saving record
  
  before_create {|t| t.status = STATUS[0] unless t.status? } # Could be fixed with the :deafult option in the migration.
  before_save :designed_responsible_takeover #####  create a trigger for Itzel to take the ticket inmediately.
  before_save :ticket_creation_change
  before_save :responsible_management
  before_save :ticket_closing
  
  def old?
  	updated_at < Date.today - 4.days
  end
 
  def finished?
    status == STATUS.last
  end
  
  private
  
  def ticket_creation_change  
    if new_record?
      changes.build   :student_comments  =>  "Tu queja ha sido enviada. Estamos resolviendo tu peticion.",
                      :admin_comments    =>  "Se levanto la queja",
                      :change_type      =>  Change::CHANGE_TYPES[0],  #Advance Change.
                      :responsible_id   =>  student.id
    end
  end
  
  def responsible_management
    if responsible_id_changed?
      actual_responsible = current_user.nil? ? responsible_id : current_user.id
      changes.build  :student_comments  => "Ha cambiado el responsable que lleva la resolucion de tu queja.",
                     :admin_comments    => "Se asigno a #{User.find(responsible_id).name} como responsable",
                     :change_type      =>  Change::CHANGE_TYPES[2], #Manager Change
                     :responsible_id   =>  actual_responsible
      self.status = STATUS[1]
    end
  end
  
  def designed_responsible_takeover    
    self.responsible  = User.ticket_taker.first if self.new_record?
  end
  
  def ticket_closing
    if !self.new_record? and self.status_changed? and self.status == STATUS.last
      changes.build   :student_comments =>  "El estudiante ha cerrado la queja",
                      :admin_comments   =>  "El estudiante ha cerrado la queja",
                      :change_type      =>  Change::CHANGE_TYPES.last,
                      :responsible      =>  current_user
    end
  end
  
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

  before_filter :require_user
    
  def index
    status  = params[:status]    
    ticket  = @current_user.admin? ? Ticket : @current_user.tickets
    @tickets = case status
                when 'pending'  then  ticket.pending
                when 'active'   then  ticket.active
                when 'finished' then  ticket.finished
              end
    respond_to do |format|
      format.html do
        if request.xhr?
              @tickets.empty? ? 
              render(:text=>"No hay Quejas") :
              render(:partial=>'tickets_table', :locals=>{:tickets=>@tickets})
        end
      end
      
      format.pdf  do
          if cookies['tickets_to_report'].nil?
            redirect_to(tickets_path, :notice =>  "Debes seleccionar las quejas que quieres exportar") 
          else
            render :pdf  => @tickets=Ticket.find(cookies['tickets_to_report'].split(",")), :disposition => 'inline'
          end
      end      
    end
  end

  def show
    @ticket = Ticket.complete.find(params[:id])
    respond_to do |format|
      format.html     
      format.pdf  { render :pdf  =>  @ticket,  :disposition  =>  "inline"}
    end
  end

  def new
    @ticket = @current_user.admin? ? Ticket.new : @current_user.tickets.build
  end
  
  ## May be removed
  def edit
    @ticket = Ticket.find(params[:id])
  end

  def create    
    @ticket = Ticket.new(params[:ticket])
    @ticket.student = (User.find_by_uid(@ticket.student_id) or @current_user)
    @ticket.save ? 
      redirect_to(@ticket, :notice => 'Tu queja ha sido enviada') :
      render(:action => "new")
  end

  def update
    @ticket = Ticket.find(params[:id])
    @ticket.current_user = @current_user
    
    if @ticket.update_attributes(params[:ticket])
      returnable = params[:ticket].has_key?(:responsible_id) ? @ticket.responsible.name : params[:ticket].values.first
    
      respond_to do |format|
        format.js   { render :text  =>  (returnable) and return }
        #format.html { redirect_to @ticket, :notice  =>  "Cambio Exitoso" }
      end
    else
      respond_to do |format|
        format.js   {render :text  => "ERROR"}
        format.html {redirect_to @ticket, :error=>"Error" }
      end
    end    
  end

  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to(tickets_url) }
    end
  end
  
  #GET
  def info        
    respond_to do |format|
      format.js do
        options={}
        Ticket::CORRESPONDING_TO.each{|option| options[option.to_sym]=option }
        render :json => options.to_json
      end
    end
  end
  
#  DEPRECATED
#  def assign_responsible
#    @ticket = Ticket.find(params[:id])
#    @managers = User.managers
#  end

  # PUT
  def close
    @ticket = Ticket.find(params[:id])
    @ticket.status  = Ticket::STATUS.last
    @ticket.current_user  = @current_user
    if @ticket.save
      redirect_to @ticket
    end
  end
    
end

app/helpers/tickets_helper.rb
module TicketsHelper
  def flag_image(ticket)
    case ticket.status
      when 'pending'
        image_tag('icons/flag_red.png')
      when 'active'
        image_tag('icons/flag_yellow.png')
      when 'finished'
        image_tag('icons/flag_green.png')
    end
  end
  
  def corresponding_to_path(ticket)
    Ticket::CORRESPONDING_MAP.each_pair do |key, arr|
      index = arr.index(ticket.corresponding_to.to_sym)
      return "#{key} >> #{arr[index]}" if index
    end
    ticket.corresponding_to
  end
end

app/views/tickets/_form.html.haml
= form_for @ticket, :html=>{:multipart => true} do |f|
  = field_set_tag do
    - if @ticket.errors.any?
      #errorExplanation
        %h2= "#{pluralize(@ticket.errors.count, 'error')} prohibited this user from being saved:"
        %ul
        - @ticket.errors.full_messages.each do |msg|
          %li= msg
    - if @current_user.admin?
      .field
        = f.label :student, "ID del Alumno"
        
        //This 2 fields change according to which action is required.
        // If we have a new Ticket, we want to assign a student.
        // If we edit, we want just to print the students name.                
        = f.text_field :student_id unless @ticket.student
        = f.hidden_field  :student_id,  :value=>@ticket.student.id if @ticket.student
        = @ticket.try(:student).try(:name)
        %span= image_tag 'loading.gif', :id=>"spinner", :style=>"display:none"
        %span#field-message
        #student-info

    .field  
      = f.label :corresponding_to, "Tipo de Queja"     
      = f.select :corresponding_to, grouped_options_for_select(Ticket::CORRESPONDING_MAP, @ticket.try(:corresponding_to) )
    
    .field
      = f.label :title, "Titulo"
      = f.text_field  :title
      
    .field
      = f.label "Descripción"
      = f.text_area :description

    .field
      = f.label :file, "Archivo de Evidencia"
      = f.file_field :file
      %ul
        - for file in @ticket.attachments
          %li= file.file_name
          
    .actions
      = f.submit t('.send')

app/views/tickets/_ticket.haml
=div_for ticket, :class=>"ticket_for_tabs" do 
  %p    
    %span.name
      #{link_to ticket.student.name, ticket_path(ticket)}
    %span.arrows &raquo; 
    #{ticket.corresponding_to}
    %span{:style=>"float:right"}
      = link_to 'Detalles', ticket_path(ticket)
      = check_box_tag('ticket_to_report', ticket.id, false) if @current_user.admin?
  %p
    hace #{time_ago_in_words ticket.updated_at}
  %p
    %span.title
      = ticket.title 
    %span.arrows
      &raquo; 
    %span.description
      = truncate ticket.description, :length=>100

app/views/tickets/_tickets_table.haml
:javascript
  $('#general-tickets-table').tablesorter({widgets:['zebra']});

%table#general-tickets-table.tablesorter
  %thead
    %tr
      %th.export
        Reportar
      %th
        Nombre
      %th
        Titulo
      %th
        Fecha
      %th
        Ver
  %tbody
    - for ticket in tickets
      %tr
        %td.checkbox= check_box_tag "ticket_to_report", ticket.id
        %td= ticket.student.name      
        %td= ticket.title
        %td{:class => ticket.old? ? "urgent" : ""}
          = ticket.created_at.to_formatted_s(:short)
          ( #{time_ago_in_words(ticket.created_at)} )
        %td= link_to image_tag('icons/zoom.png'), ticket

app/views/tickets/edit.html.haml
- content_for  :script do
  =javascript_include_tag  'jq-scripts/charCount.js'
  :javascript
    $(document).ready(function(){$("#ticket_description").charCount({allowed: 300, counterText: "Límite: "});});  

- content_for :nav do
  = back_button(ticket_path(@ticket) )
.grid_12
  %h1= t '.title'  
  = render 'form'

app/views/tickets/index.html.haml
- if @current_user.admin?
  -include_script 'jquery.cookie.js', 'jq-scripts/report_generation.js', 'jq-scripts/tabs.js'
- else
  -include_script 'jquery.cookie.js', 'jq-scripts/tabs.js'
  
-include_css 'tablesorter/blue/style.css'
-include_script 'tablesorter.min.js'    

= content_for :nav do 
  =link_to t('.new_ticket'), new_ticket_path
  - if @current_user.admin?
    = link_to "Managers", managers_path
    = link_to 'Reporte',  report_tickets_path(:format=>:pdf)

// %div{:class=> @current_user.admin? ? "grid_8" : "grid_12" }
.grid_12
  %h1= @current_user.admin? ? "Panel de Quejas" : "Mis Quejas"
  #tabs
    %ul 
      %li
        =link_to  "Sin Revisar", tickets_by_status_path(:status=>:pending)
      %li
        =link_to "En Proceso", tickets_by_status_path(:status=>:active), :id=>"proceso"
      %li
        =link_to  "Terminadas", tickets_by_status_path(:status=>:finished)
      %li
        <img id="spinner" src="/images/loading.gif" style="display:none" />

app/views/tickets/new.html.haml
- include_script 'jq-scripts/charCount.js', 'student_recognition.js'
- content_for  :script do
  :javascript
    $(document).ready(function(){$("#ticket_description").charCount({allowed: 300, counterText: "Límite: "});});  

- content_for :nav do
  = back_button
  
.grid_12    
  %h1 Nueva Queja
  
  = render 'form'

app/views/tickets/show.html.haml
- content_for :nav do
  = back_button(tickets_path)
  - if @current_user.admin?
    = link_to t('edit'), edit_ticket_path(@ticket), :id=>'edit-button'
    = link_to 'PDF',  ticket_path(@ticket, :format => :pdf)
    = link_to t('destroy'), ticket_path(@ticket), :method=>'delete', :confirm => t('are_you_sure'), :id=>"delete-button"
  - elsif @ticket.finished?
    = link_to "ReAbrir Queja", close_ticket_path(@ticket), :id=>'close-ticket-button', :method=>"post"
  -else
    = link_to "Cerrar Queja", close_ticket_path(@ticket), :id=>'close-ticket-button', :method=>"post"
- if @current_user.admin?
  -content_for :script do
    =javascript_include_tag "http://www.appelsiini.net/download/jquery.jeditable.mini.js"
    :javascript
      $(document).ready(function(){
        $('#ticket_responsible').editable(window.location.pathname,{
            name        : "ticket[responsible_id]",
            submitdata  : {"_method": 'put', "authenticity_token" : #{form_authenticity_token.to_json} },
            loadurl     : '/managers' ,
            type        : 'select'    ,
            submit      : "OK"        ,
            cancel      : "Cancelar"  ,
            tooltip     :  'Click para cambiar'
        }).hover(function(){$(this).addClass('editable')},function(){$(this).removeClass('editable')})
        $('#ticket_corresponding_to').editable(window.location.pathname,{
            name        : "ticket[corresponding_to]",
            loadurl     : "/ticket/info/",
            submitdata  : {"_method": 'put', "authenticity_token" : #{form_authenticity_token.to_json} },
            type        : 'select'  ,
            submit      : "Ok",
            cancel      : "Cancelar"
        }).hover(function(){$(this).addClass('editable')},function(){$(this).removeClass('editable')})
        
        $('.ticket #toggleComment').click(function(){
          $(this).next('#new_comment').slideToggle()
        })
      })

=div_for @ticket do 
  .grid_12
    %h1 
      Detalles de Queja
  .grid_12
    %h2 #{image_tag('icons/information.png')} Estado actual
    
    %p
      %span=flag_image(@ticket)
      = t @ticket.status
      \- 
      =Ticket::STATUS_MSGS[@ticket.status.to_sym]
  .grid_7
    %h2 #{image_tag('icons/page_white_text.png')} Datos Generales
    %table
      %tr
        %td
          %h3 Titulo
        %td
          %p= @ticket.title
      %tr
        %td
          %h3 Estudiante
        %td
          %p= @ticket.student.name + " - " + @ticket.student.uid
      %tr
        %td
          %h3 Administrativo Responsable
        %td#ticket_responsible
          %p
            - if @ticket.responsible
              = @ticket.responsible.name
            - else
              -if @current_user.admin?
                = button_to("Tomar Queja", {:action=>:update, :ticket=>{:responsible_id=>@current_user.id}}, :method=>:put)
              -else
                = "Sin Responsable"     
      %tr
        %td
          %h3 Tema
        %td#ticket_corresponding_to
          %p=corresponding_to_path(@ticket)

      %tr
        %td
          %h3 Descripcion
        %td
          = @ticket.description

    %h2 #{image_tag('icons/arrow_right.png')} Evolucion de la queja
    =render @ticket.changes
  .grid_5
    -if !!@ticket.responsible and @current_user.admin?
      %p= link_to "Registrar Cambio", new_ticket_change_path(@ticket), :method=>:get, :class=>'jq-button' 
    
    %h2 #{image_tag('icons/disk_multiple.png')} Archivos de Evidencia
    =render @ticket.attachments

    %h2 #{image_tag('icons/comments.png')} Comentarios sobre la queja
    .ticket_comments
      =render @ticket.comments
    =render :partial=>"/comments/comment_form", :locals=>{:post=>@ticket}  
    
        
    %p= button_to "Agregar Archivo", edit_ticket_path(@ticket), :method=>:get